x-default-network: &default_network
  networks:
    - docker_net

version: '3'
name: dripdrop-ui
services:
  web:
    container_name: web
    build:
      context: .
    entrypoint: npm run serve
    restart: always
    environment:
      VIRTUAL_HOST: dripdrop.icu,www.dripdrop.icu
      VIRTUAL_PATH: /
      LETSENCRYPT_HOST: dripdrop.icu,www.dripdrop.icu
    expose:
      - 80
    <<: *default_network

networks:
  docker_net:
    external: true
