version: 2

jobs:
  build and deploy:
    docker:
      - image: node
    steps:
      - checkout
      - run:
          name: Install Client Dependencies and Build
          command: npm install && NODE_ENV=production npm run build
      - run:
          name: Create Build Directory on VM
          command: ssh -o StrictHostKeyChecking=no -v $SSH_USER@$SSH_HOST "mkdir -p ~/build"
      - run:
          name: Copy Client to VM Build Directory
          command: scp -o StrictHostKeyChecking=no -vr ./build $SSH_USER@$SSH_HOST:/dripdrop

workflows:
  version: 2
  deploy:
    jobs:
      - build and deploy:
          filters:
            branches:
              only: main # only deploy on the main branch
