name: Web

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Client Dependencies and build
        run: npm install --production=false && npm run build
      - name: Upload Build artifact
        if: ${{ github.ref }} == '/refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          retention-days: 1
  deploy:
    if: ${{ github.ref }} == '/refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Build artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Export ssh key
        run: |
          echo "${{ secrets.SSH_KEY }}" >> ssh_key && sudo chmod 400 ssh_key
      - name: Create Build Directory on VM
        run: ssh -o StrictHostKeyChecking=no -i ./ssh_key -v $SSH_USER@$SSH_HOST "mkdir -p ~/dist"
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
      - name: Copy Client to VM Build Directory
        run: scp -o StrictHostKeyChecking=no -i ./ssh_key -vr ./dist $SSH_USER@$SSH_HOST:~
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
